---
name: Matt
surname: Ashby
position: "Lecturer in Crime Science\\tabularnewline University College London"
address: "Department of Security and Crime Science\\tabularnewline 35 Tavistock Square, London WC1H 9EZ"
# phone: +44 20 3108 3890
www: lesscrime.info
email: "matthew.ashby@ucl.ac.uk"
twitter: lesscrime
github: mpjashby
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman()
---

```{r eval=FALSE, include=FALSE}
# AFTER KNITTING THIS FILE, run the following line to copy the resulting PDF
# into the correct location
file.copy(here::here("CV/CV.pdf"), here::here("static/files/cv.pdf"), 
					overwrite = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library("lubridate")
library("rorcid")
library("vitae")
library("tidyverse")

my_orcid <- "0000-0003-4201-9239"
```


# Employment

```{r employment}
orcid_employments(my_orcid) %>% 
	pluck(my_orcid, "affiliation-group", "summaries") %>% 
	{ do.call("bind_rows", .) } %>%
	brief_entries(
		what = `employment-summary.role-title`,
		when = paste0(
			format(ymd(paste(`employment-summary.start-date.year.value`,
											 `employment-summary.start-date.month.value`,
											 `employment-summary.start-date.day.value`)), "%b %Y"), 
			"–",
			ifelse(is.na(`employment-summary.end-date.year.value`),
						 "present",
						 format(ymd(paste(`employment-summary.end-date.year.value`,
											 `employment-summary.end-date.month.value`,
											 `employment-summary.end-date.day.value`)), "%b %Y"))
		),
		with = glue::glue("{`employment-summary.department-name`}, {`employment-summary.organization.name`}")
	)
```


# Education

```{r education}
orcid_educations(my_orcid) %>% 
	pluck(my_orcid, "affiliation-group", "summaries") %>% 
	{ do.call("rbind", .) } %>% 
	brief_entries(
    what = `education-summary.role-title`,
    when = glue::glue("{`education-summary.start-date.year.value`}–{`education-summary.end-date.year.value`}"),
    with = `education-summary.organization.name`
	)
```


# Professional qualifications

```{r qualifications}
orcid_qualifications(my_orcid) %>% 
	pluck(my_orcid, "affiliation-group", "summaries") %>% 
	{ do.call("rbind", .) } %>% 
	brief_entries(
		what = `qualification-summary.role-title`,
		when = `qualification-summary.start-date.year.value`,
		with = `qualification-summary.organization.name`
	)
```


# Publications

ORCID: `r my_orcid`

```{r publications}
# Biber cannot handle file paths containing spaces, so we will copy 
# citations.bib to a temporary location that Biber can read
# citations_file <- tempfile(fileext = ".bib")
# invisible(file.copy(from = here::here("CV/citations.bib"), to = citations_file))

# ~/Documents/citations.bib is a symlink to the citations.bib file in the CV
# directory of this RStudio project, since Biber is unable to handle file paths
# containing spaces
# bibliography_entries(citations_file) %>% 
	# arrange(desc(issued), author) %>% 
	# mutate(
	# 	`container-title` = ifelse(
	# 		is.na(`container-title`) & type == "article-journal", 
	# 		str_glue("pre-print on {publisher}"), 
	# 		`container-title`
	# 	)
	# )

scholar::get_publications("dwcesrQAAAAJ") %>% 
  arrange(desc(year)) %>% 
  detailed_entries(
    what = title,
    when = year,
    with = author,
    where = str_glue("{journal}{ifelse(number != '', str_glue(', {number}'), '')}")
  )
```


# Funding

Funding awarded, typically jointly with colleagues.

```{r funding}
tribble(
	~type, ~title, ~start_date, ~end_date, ~value, ~funder,
	"Research project", "Problem-Oriented Policing in England and Wales", 2019, 2020, "£246,000", "Police Transformation Fund",
	"Vice Chancellor's PhD studentship", "Building evidence to support police initial response to incidents", 2018, 2021, "£60,000", "Nottingham Trent University",
	"Vice Chancellor's PhD studentship", "Crime reduction and public reassurance in a diverse society", 2017, 2020, "£60,000", "Nottingham Trent University",
	"Knowledge transfer partnership", "Problem Solving for Neighbourhood Policing", 2012, 2013, "£16,000", "Engineering and Physical Sciences Research Council"
) %>% 
	arrange(desc(start_date)) %>% 
	brief_entries(
		what = str_glue("{`type`}: {`title`}"),
		when = str_glue("{`start_date`}–{`end_date`}"),
		with = str_glue("{`value`} funding from {`funder`}")
	)
```


# Professional service

```{r service}
tribble(
  ~start_date, ~end_date, ~title, ~description, ~url,
  2017, "ongoing", "CrimPapers", "Maintainer of the CrimPapers alert service for new articles in 100+ criminology journals", "https://lesscrime.info/crimpapers/",
  2018, "ongoing", "Crime Open Database", "Maintainer of the Crime Open Database of harmonised open crime data from 16 large cities in the United States, as well as the associated `crimedata` R package", "http://osf.io/zyaqn/",
  2019, "ongoing", "Crime Science", "Associate editor of the Crime Science journal, published by Springer", NA,
  2019, "ongoing", "London Problem Solving Awards", "Judge for the London Problem Solving Awards run jointly by the Metropolitan Police Service, British Transport Police and City of London Police", NA
) %>% 
  arrange(start_date) %>% 
  brief_entries(
    what = str_glue("{`title`}"),
    when = str_glue("{`start_date`}–{`end_date`}"),
    with = str_glue("{`description`}. {ifelse(!is.na(url), {`url`}, '')}")
  )
```
