---
title: "Chart: Police cuts haven't hit everywhere equally"
author: Matt Ashby
date: '2019-08-19'
slug: police-numbers
categories: ["Crime and justice chart of the week"]
tags:
  - police
  - trends
  - criminal justice
---


```{r set knitr options, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, include=FALSE)
```

```{r set chart parameters}
chart_details <- list(
	id = "police-numbers",
	title = "Police cuts haven't hit everywhere equally",
	subtitle = "There are almost 22,000 fewer police officers in England and Wales than in 2010, but numbers haven't dropped equally across police forces. One force (Surrey) has the same number of officers now as 10 years ago, while officer numbers in forces like Humberside are increasing after steep cuts. But in almost half of forces, numbers are still falling despite a decade of often above-average cuts already.",
	source_url = "https://www.gov.uk/government/statistics/police-workforce-open-data-tables",
	source_title = "Home Office, 2019"
)
```

```{r load packages and helper}
# custom packages not loaded by helpers.R
library("ggrepel")
library("lubridate")
library("reticulate")

# load this after loading custom packages
source(here::here("helpers.R"))
```

```{r get and tidy data}
if (!file.exists(paste0(chart_details$id, "-data.csv.gz"))) {
	
	# download most-recent data
	new_data_file <- tempfile(fileext = ".ods")
	new_csv_file <- paste0(new_data_file, ".csv")
	GET("https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/817734/open-data-table-police-workforce.ods", write_disk(new_data_file))
	
	# convert new data from ODS to CSV and read
	source_python(here::here("ods_to_csv.py"))
	ods_to_csv(new_data_file, "Data", new_csv_file)
	tidy_data <- new_csv_file %>% 
		read_csv(na = "N/A") %>% 
		clean_names() %>% 
		filter(
			worker_type == "Police officer" 
		) %>% 
		rename(year = as_at_31_march) %>% 
		group_by(year, force_name) %>%
		summarise(officers = sum(total_fte)) %>% 
		ungroup()
	
	# save tidy data
	write_csv(tidy_data, paste0(chart_details$id, "-data.csv.gz"))	
	
} else {
	
	# load tidy data
	tidy_data <- read_csv(paste0(chart_details$id, "-data.csv.gz"))
	
}
```


```{r prepare plot data}
chart_data <- tidy_data %>% 
	ungroup() %>% 
	filter(year >= 2010, force_name != "London, City of", 
				 force_name != "British Transport Police") %>% 
	mutate(
		force_name = str_replace(force_name, "^North ", "N "),
		force_name = str_replace(force_name, "^South ", "S "),
		force_name = str_replace(force_name, "^West ", "W "),
		force_name = str_replace(force_name, " Yorkshire$", " Yorks"),
		force_name = recode(force_name, 
  		"Avon & Somerset" = "Avon & Som",
			"Bedfordshire" = "Beds",
			"Cambridgeshire" = "Cambs",
			"Derbyshire" = "Derbys",
			"Devon & Cornwall" = "Dvn & Corn",
			"Gloucestershire" = "Gloucs",
			"Greater Manchester" = "G Mnchstr",
			"Hampshire" = "Hants",
	  	"Hertfordshire" = "Herts",
			"Lancashire" = "Lancs",
			"Leicestershire" = "Leics",
			"Lincolnshire" = "Lincs",
  		"Metropolitan Police" = "Met Police",
  		"Northamptonshire" = "Northants",
			"Nottinghamshire" = "Notts",
			"Staffordshire" = "Staffs",
			"Thames Valley" = "Thames V",
			"Warwickshire" = "Warwicks",
			"W Midlands" = "W Mids"
  	)
	) %>% 
	group_by(force_name) %>% 
	mutate(
		perc_change = (officers - first(officers)) / first(officers),
		diff_perc_change = perc_change - lag(perc_change),
		trajectory = sum(nth(diff_perc_change, -3), nth(diff_perc_change, -2), 
										 nth(diff_perc_change, -1)),
		force_group = fct_case_when(
			last(perc_change) > -0.05 & mean(perc_change, na.rm = TRUE) > -0.05 ~ 
				"no major loss\nof officers (<5%)",
			# trajectory >= 0.015 & mean(perc_change) <= -0.05 ~ 
			trajectory >= 0.015 ~ 
				"recovering after\nprevious losses",
			(trajectory >= -0.015 & last(perc_change) <= -0.05) |
				(last(perc_change) > nth(perc_change, -2)) ~ 
				"now stable after\nprevious losses",
			trajectory < -0.015 ~ "still\ndecreasing",
			TRUE ~ "other"
		),
		last = ifelse(year == last(year), TRUE, NA),
		label = ifelse(last == TRUE, sprintf("%+.0f%%", perc_change * 100), NA),
		label = ifelse(label == "-0%", "0%", label), 
		label_vjust = ifelse(last(perc_change) < 0, "bottom", "top")
	) %>% 
	ungroup() %>% 
	# calculate average change for each year for England and Wales
	group_by(year) %>% 
	mutate(ew_officers = sum(officers)) %>% 
	ungroup() %>% 
	mutate(
		ew_perc_change = (ew_officers - first(ew_officers)) / first(ew_officers)
	) %>% 
	select(-ew_officers) %>% 
	ungroup() %>% 
	mutate(force_name = ifelse(force_group == "still decreasing", 
														 paste0("bold(\"", force_name, "\")"), 
														 paste0("\"", force_name, "\"")))

forces_in_order <- chart_data %>% 
	filter(year == last(year)) %>% 
	arrange(desc(perc_change)) %>% 
	pull("force_name")

chart_data <- chart_data %>% 
	mutate(force_name = fct_relevel(force_name, forces_in_order))
```

```{r build plot}
chart <- chart_data %>% 
	ggplot(aes(x = year, y = perc_change, ymin = 0, ymax = perc_change, 
						 colour = force_group, fill = force_group)) + 
	geom_ribbon(colour = NA, alpha = 0.1) +
	geom_line(aes(y = ew_perc_change, 
								linetype = "England & Wales\naverage change"), 
						colour = "grey50") + 
	geom_line(size = 0.75) + 
	geom_point(aes(shape = last), na.rm = TRUE, show.legend = FALSE) +
	geom_text(aes(y = 0, label = label, vjust = label_vjust), 
						size = elements$label_text_size * (7 / 9), 
						hjust = "right", na.rm = TRUE, show.legend = FALSE) + 
	scale_x_continuous(breaks = c(2010, 2019), labels = c("'10", "'19")) + 
	scale_y_continuous(
		breaks = c(0, min(chart_data$perc_change)), 
		labels = scales::percent_format(accuracy = 1)
	) + 
	scale_colour_manual(
		aesthetics = c("colour", "fill"),
		values = unname(ucl_colours_list[c("Mid Blue", "Orange", 
																			 "Bright Blue", "Bright Red")]), 
		guide = guide_legend(ncol = 1), 
		name = "trajectory, based on\npast three years"
	) +
	scale_linetype_manual(values = "11") +
	coord_cartesian(clip = "off") +
	facet_wrap(vars(force_name), labeller = label_parsed) +
  labs(
    title = chart_details$title,
    subtitle = format_subtitle(chart_details$subtitle),
    x = NULL,
    y = "change in number of police officers relative to 2010",
    linetype = NULL
  ) +
	theme_cjcharts() +
	theme(
		axis.text = element_text(size = 7),
		legend.key.width = unit(18, "points"),
		legend.text = element_text(margin = margin(t = 4, b = 4)),
		legend.title.align = 0,
		legend.position = "right",
		legend.margin = margin(t = 4, r = 0, b = 4, l = 0),
		legend.box.margin = margin(),
		panel.grid.minor.y = element_blank(),
		panel.spacing = unit(0.4, "lines"),
		strip.text = element_text(size = 8),
		strip.background = element_blank()
	)

```

`r chart_details$subtitle`

```{r display plot, echo=FALSE, include=TRUE}
add_logo(chart + labs(title = NULL, subtitle = NULL), 
				 chart_details$source_title, chart_details$id)
```

[larger image](../`r chart_details$id`.png) | [annotated R code to produce this chart](https://github.com/mpjashby/lesscrime.info/blob/master/content/post/`r chart_details$id`.Rmd)

Data source: [`r chart_details$source_title`](`r chart_details$source_url`)

```{r export chart}
# save PNG for social media
ggsave(
	filename = paste0(chart_details$id, ".png"), 
	plot = add_logo(chart, chart_details$source_title, chart_details$id), 
	device = "png", width = 600 / 72, height = 600 / 72, units = "in"
)
```

