---
title: "Chart: Over 10 years, basic police pay has fallen by 22% in real terms"
author: Matt Ashby
date: '2019-09-16'
slug: police-pay
categories: ["Crime and justice chart of the week"]
tags:
  - criminal justice
  - police
---

```{r set knitr options, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, include=FALSE)
```

```{r set chart parameters}
chart_details <- list(
	id = "police-pay",
	title = "Over 12 years, pay for new police officers has fallen 22%",
	subtitle = "A combination of government-led changes to pay mean a police constable who has just completed initial training in England and Wales is paid about £7,200 less now than they would have been in 2010, once inflation is taken into account. These figures exclude overtime and special allowances, but those are unlikely to have made up for decreasing basic pay.",
	source_url = "https://www.whatdotheyknow.com/request/police_constable_pay_scales",
	source_title = "Police Federation, Home Office"
)
```

```{r load packages and helper}
# custom packages not loaded by helpers.R
library("lubridate")
library("readxl")

# load this after loading custom packages
source(here::here("helpers.R"))
```

```{r get and tidy data}
if (!file.exists(paste0(chart_details$id, "-data.csv.gz"))) {
	
	# the data are provided as a series of scanned PDFs of Federation circulars,
	# so must be entered manually
	# 2019 police data from https://www.gov.uk/government/publications/police-remuneration-review-body-report-2019-england-and-wales
	police_pay <- tribble(
		~date, ~new, ~mid, ~top,
		# "2005-04-01", 22107, 31092,
		"2005-09-01", 22770, 27213, 32025,
		"2006-09-01", 23454, 28029, 32985,
		"2007-12-01", 24039, 28731, 33810,
		"2008-09-01", 24675, 29493, 34707,
		"2009-09-01", 25317, 30261, 35610,
		"2010-09-01", 25962, 31032, 36519,
		"2011-09-01", 25962, 31032, 36519,
		"2012-09-01", 25962, 31032, 36519,
		# "2013-04-01", 22000, 36885,
		"2013-09-01", 22221, 31341, 36885,
		"2014-09-01", 22443, 31653, 37254,
		"2015-09-01", 22668, 31971, 37626,
		"2016-09-01", 22896, 31971, 37626,
		"2017-09-01", 23124, 32616, 38382,
		"2018-09-01", 23586, 33267, 39150, # officers with 5 years' service will be at point 6 on new scale
		"2019-09-01", 24177, 34098, 40128,
		"2020-09-01", 24780, 34950, 41130,
		"2021-09-01", 24780, 34950, 41130
	) %>% 
		gather("service", "pay", -date) %>% 
		mutate(date = ymd(date), year = year(date))
	
	# get ONS CPIH inflation indices, where 2015 = 100
	deflator <- read_csv("https://www.ons.gov.uk/generator?format=csv&uri=/economy/inflationandpriceindices/timeseries/l522/mm23", skip = 8, col_names = c("year", "index")) %>% 
		slice(1:33) %>% 
		# add 2021 data based on Q2 figure at
		# https://www.ons.gov.uk/economy/inflationandpriceindices/timeseries/l522/mm23
		add_row(year = "2021", index = 110.9) %>% 
		mutate(year = as.numeric(year))
	
	# adjust pay for inflation using method described at 
	# https://researchbriefings.parliament.uk/ResearchBriefing/Summary/SN04962
	tidy_data <- police_pay %>% 
		left_join(deflator, by = "year") %>% 
		mutate(
			date = as_date(ifelse(is.na(date), ymd(paste(year, "04 01")), date)),
			index19 = index / last(index),
			pay_adj = pay / index19
		)
	
	# save tidy data
	write_csv(tidy_data, paste0(chart_details$id, "-data.csv.gz"))	

} else {
	
	# load tidy data
	tidy_data <- read_csv(paste0(chart_details$id, "-data.csv.gz"))
	
}

```

```{r prepare data for chart}
chart_data <- tidy_data %>% 
	mutate(
		date = ymd(paste(year, "09", "01")),
		party = fct_case_when(
			year < 2010 ~ "Labour",
			year < 2015 ~ "Coalition",
			TRUE ~ "Conservative"
		),
		service = fct_case_when(
			service == "new" ~ "pay after initial training",
			service == "mid" ~ "pay after 5 years' service",
			service == "top" ~ "pay after 10 years' service",
			TRUE ~ NA_character_
		)
	) %>% 
	# calculate changes
	group_by(service) %>% 
	mutate(
		perc_change = (pay_adj - lag(pay_adj)) / lag(pay_adj),
		cash_change = (pay_adj - lag(pay_adj)),
		perc_change = ifelse(year == first(year), NA, perc_change),
		cash_change = ifelse(year == first(year), NA, cash_change),
		change_label = scales::comma(cash_change, accuracy = 1),
		change_label = case_when(
			year == first(year) ~ scales::comma(pay_adj, accuracy = 1, prefix = " £", suffix = " in 2021 terms"),
			cash_change > 0 ~ paste0(" +", change_label),
			cash_change < 0 ~ str_replace(change_label, "^-", " –"),
			TRUE ~ ""
		),
		change_label = ifelse(
			year == last(year), 
			paste(
				change_label, "=", scales::comma(pay_adj, accuracy = 1, prefix = "£"),
				str_replace(perc_change(first(pay_adj), last(pay_adj), accuracy = 1, 
																prefix = "(", suffix = "%)"), "\\-", "–")
			), 
			change_label
		)
	) %>% 
	ungroup()

# RULES FOR CHART LABELS
# Label positions must be calculated manually, using the space created by 
# calling expand_scale() on the relevant scale(s). `curve` can either be 'left',
# 'right' or 'straight' and these will be plotted by separate calls to 
# `geom_curve()` or `geom_segment()` since the direction of curvature cannot be
# set via an aesthetic

# add chart labels
chart_labels <- tribble(
	~x, ~y, ~xend, ~yend, ~service, ~label, ~hjust, ~vjust, ~curve,
	ymd("2005-09-01"), 32500, ymd("2007-09-01"), 47000, "pay after initial training", balance_lines("an officer completing training in 2005 earned the equivalent of £31,800 in 2021 terms", 2), "left", "bottom", "left",
	ymd("2010-09-01"), 38500, ymd("2011-03-01"), 42000, "pay after 5 years' service", balance_lines("the 2010 pay freeze began to erode salaries for existing officers in real terms", 4), "left", "bottom", "left",
	ymd("2013-09-01"), 26000, ymd("2015-03-01"), 39000, "pay after initial training", balance_lines("in 2013, salaries for new officers were reduced by £4,900 in 2021 terms", 3), "left", "bottom", "left",
	ymd("2018-09-01"), 42000, ymd("2017-09-01"), 45500, "pay after 10 years' service", balance_lines("below-inflation increases have reduced salaries slightly further since the pay freeze ended", 3), "right", "bottom", "right"
) %>% 
	mutate(
		party = "Labour",
		service = factor(service, levels = levels(chart_data$service))
	)
```

```{r build plot}
chart <- chart_data %>% 
	ggplot(aes(date, pay_adj, fill = party)) + 
	geom_col() + 
	geom_text(aes(label = change_label), colour = "white", 
						size = elements$label_text_size * 0.9, angle = -90, hjust = 0) +
	# add explanatory labels
	geom_curve(aes(x = x, y = y, xend = xend, yend = yend),
						 data = filter(chart_labels, curve == "right"), inherit.aes = FALSE,
						 curvature = elements$label_line_curvature,
						 colour = elements$label_line_colour,
						 arrow = elements$label_arrow, show.legend = FALSE) +
	geom_segment(aes(x = x, y = y, xend = xend, yend = yend),
						 data = filter(chart_labels, curve == "straight"),
						 inherit.aes = FALSE, colour = elements$label_line_colour,
						 arrow = elements$label_arrow, show.legend = FALSE) +
	geom_curve(aes(x = x, y = y, xend = xend, yend = yend),
						 data = filter(chart_labels, curve == "left"), inherit.aes = FALSE,
						 curvature = elements$label_line_curvature * -1,
						 colour = elements$label_line_colour,
						 arrow = elements$label_arrow, show.legend = FALSE) +
	geom_label(aes(x = xend, y = yend, label = label, hjust = hjust,
								 vjust = vjust),
						data = chart_labels, inherit.aes = FALSE,
						colour = elements$label_text_colour,
						fill = elements$label_text_fill, size = elements$label_text_size,
						lineheight = elements$label_text_lineheight,
						label.size = NA, show.legend = FALSE) +
	# end of explanatory labels
	coord_cartesian(clip = "off") +
	scale_x_date(date_breaks = "2 years", date_labels = "'%y", 
							 expand = expansion(mult = c(0, 0.01))) +
	scale_y_continuous(
		breaks = seq(0, 40e3, by = 5e3),
		labels = scales::number_format(accuracy = 1, scale = 1/1000, prefix = "£", suffix = "k"),
		limits = c(0, NA), 
		expand = expansion(add = c(0, 6000))
	) + 
	scale_fill_manual(
		values = c("Labour" = "#DC241F", "Coalition" = "#8DB9CA",
							 "Conservative" = "#0087DC"),
		labels = c("Labour" = "Labour, 1997–2010  ", 
							 "Coalition" = "Coalition, 2010–2015  ", 
							 "Conservative" = "Conservative, 2015–present  ")
	) +
	facet_grid(cols = vars(service)) +
	labs(
		title = chart_details$title,
		subtitle = format_subtitle(chart_details$subtitle, .width = 120),
		legend = NULL,
		x = NULL,
		y = "gross salary before allowances, inflation adjusted to 2021",
		fill = NULL
	) +
	theme_cjcharts() +
	theme(
		panel.grid.major = element_blank(),
		panel.grid.minor = element_blank()
	)

```

`r chart_details$subtitle`

```{r display plot, echo=FALSE, include=TRUE}
add_logo(chart + labs(title = NULL, subtitle = NULL), 
				 chart_details$source_title, chart_details$id)
```

[larger image](../`r chart_details$id`.png)
| [annotated R code to produce this chart](https://github.com/mpjashby/lesscrime.info/blob/master/content/post/`r chart_details$id`.Rmd)

Data source: [`r chart_details$source_title`](`r chart_details$source_url`)

Pay for years before 2019 has been adjusted for inflation using the [Office for
National Statistics preferred CPIH measure](https://www.ons.gov.uk/economy/inflationandpriceindices/timeseries/l522/mm23).
For 2019, second-quarter inflation estimates have been used.

```{r export chart}
# save PNG for social media
ggsave(
	filename = paste0(chart_details$id, "-2021.png"), 
	plot = add_logo(chart, chart_details$source_title, chart_details$id), 
	device = "png", width = 600 / 72, height = 400 / 72, units = "in", bg = "white"
)
```
