---
title: "Chart: In serious cases, justice is often slow"
author: Matt Ashby
date: '2020-03-09'
categories:
  - Crime and justice chart of the week
tags:
  - criminal justice
  - courts
  - prosecutions
  - trials
---
	
```{r set knitr options, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, include=FALSE)
```

```{r set chart parameters}
chart_details <- list(
	id = "prosecution-times",
	title = "In serious cases, justice is often slow",
	subtitle = "Some serious crime investigations are surprisingly quick: half of murder prosecutions involve a suspect being charged in five days or fewer. But for many serious crimes, justice is often slow: half of fraud prosecutions don't conclude until almost two years after the crime occurred.",
	source_url = "https://www.gov.uk/government/statistics/criminal-court-statistics-quarterly-july-to-september-2019",
	source_title = "Ministry of Justice, 2019"
)
```

```{r load packages and helper}
# custom packages not loaded by helpers.R

# load this after loading custom packages
source(here::here("helpers.R"))
```

```{r get and tidy data}
# get data
if (!file.exists(paste0(chart_details$id, "-data.csv.gz"))) {
	
	# the data in the file https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/851931/time_offence_tool.xlsx are hidden in a pivot table, so we load a version manually extracted from the pivot table, including data for the most-recent available year
	
	tidy_data <- read_csv("prosecution-times-raw-data.csv") %>% 
		clean_names() %>% 
		rename(offence = row_labels)
	
	# save tidy data
	write_csv(tidy_data, paste0(chart_details$id, "-data.csv.gz"))	
	
} else {
	
	# load tidy data
	tidy_data <- read_csv(paste0(chart_details$id, "-data.csv.gz"))
	
}
```

```{r prepare data for chart}
chart_data <- tidy_data %>% 
	mutate(
		offence_to_charge = median_offence_to_charge_days,
		offence_to_first_hearing = 
			median_offence_to_charge_days + median_charge_to_first_listing_days,
		offence_to_main_hearing = 
			median_offence_to_charge_days + median_charge_to_first_listing_days +
			median_sending_to_crown_court_to_main_hearing_days,
		offence_to_completion = 
			median_offence_to_charge_days + median_charge_to_first_listing_days +
			median_sending_to_crown_court_to_main_hearing_days +
			median_main_hearing_to_completion_days
	) %>% 
	select(offence, offence_to_charge, offence_to_first_hearing, 
				 offence_to_main_hearing, offence_to_completion) %>% 
	mutate(
		offence = recode(
			offence,
			"All Crown Court cases" = "**all Crown Court cases**",
			"Violence against the person: All" = "all violence", 
			"Violence against the person: Murder" = "murder", 
			"Sexual offences: All" = "sex offences", 
			"Robbery" = "robbery",
			"Theft Offences" = "theft",
			"Criminal damage and arson" = "criminal damage",
			"Drug offences" = "drugs", 
			"Possession of weapons" = "weapons",
			"Public order offences" = "public order",
			"Fraud Offences" = "fraud",
			# "Summary motoring" = "road traffic",
			.default = NA_character_
		),
		offence = fct_reorder(offence, offence_to_completion, .desc = TRUE)
	) %>% 
	pivot_longer(-offence, names_to = "period", values_to = "days") %>% 
	filter(!is.na(offence)) %>% 
	mutate(
		months = days / (365 / 12),
		period = recode_factor(
			period,
			"offence_to_charge" = "offence to suspect being charged",
			"offence_to_first_hearing" = 
				"suspect being charged to first court appearance",
			"offence_to_main_hearing" = 
				"first court appearance to main hearing",
			"offence_to_completion" = 
				"main hearing to case being completed"
		)
	) %>% 
	arrange(offence, period) %>% 
	group_by(offence) %>% 
	mutate(prev = ifelse(is.na(lag(months)), 0, lag(months))) %>% 
	ungroup()

# add chart labels
chart_labels <- tribble(
	~x, ~y, ~xend, ~yend, ~label, ~hjust, ~vjust, ~curve,
	12.1, 2.3, 13.3, 3.4, balance_lines("half of sex offence prosecutions take over a year to get to court", 2), "left", "center", "left",
	6.1, 3.15, 7.4, 4.6, balance_lines("most murder investigations take only a few days, with a trial about six months later", 3), "left", "center", "left",
	5.5, 5, 6.5, 6, balance_lines("drugs investigations take longer, due to backlogs in testing seized drugs", 2), "left", "bottom", "right",
	4.8, 7.2, 6.5, 8.5, balance_lines("overall, the longest period during the Crown Court prosecution process is the wait between the first appearance at court and the main hearing", 3), "left", "center", "left"
	# 2.4, 10, 3.5, 10.25, balance_lines("for weapons possession, both investigations and trials are typically brief, with most time spent waiting for a main court hearing", 2), "left", "center", "left"
)
```

```{r build plot}
chart <- ggplot(
	chart_data, 
	aes(x = prev, y = offence, xend = months, yend = offence, colour = period)
) +
	geom_segment(
		size = 1.25, 
		arrow = arrow(angle = 40, length = unit(6, "points"), type = "closed")
	) +
	# add explanatory labels
	geom_curve(aes(x = x, y = y, xend = xend, yend = yend),
						 data = filter(chart_labels, curve == "right"), inherit.aes = FALSE, 
						 curvature = elements$label_line_curvature, 
						 colour = elements$label_line_colour, 
						 arrow = elements$label_arrow, show.legend = FALSE) +
	geom_segment(aes(x = x, y = y, xend = xend, yend = yend),
							 data = filter(chart_labels, curve == "straight"), 
							 inherit.aes = FALSE, colour = elements$label_line_colour, 
							 arrow = elements$label_arrow, show.legend = FALSE) +
	geom_curve(aes(x = x, y = y, xend = xend, yend = yend),
						 data = filter(chart_labels, curve == "left"), inherit.aes = FALSE, 
						 curvature = elements$label_line_curvature * -1, 
						 colour = elements$label_line_colour, 
						 arrow = elements$label_arrow, show.legend = FALSE) +
	geom_label(aes(x = xend, y = yend, label = label, hjust = hjust, 
								 vjust = vjust),
						 data = chart_labels, inherit.aes = FALSE, 
						 colour = elements$label_text_colour,
						 fill = elements$label_text_fill, size = elements$label_text_size, 
						 lineheight = elements$label_text_lineheight,
						 label.size = NA, show.legend = FALSE) +
	# end of explanatory labels
	scale_x_continuous(
		breaks = seq(0, 24, by = 3),
		minor_breaks = seq(0, 24, by = 1),
		expand = expansion(mult = c(0, 0.02))
	) +
	scale_colour_manual(
		guide = guide_legend(nrow = 2),
		values = unname(ucl_colours_list[c("Mid Blue", "Bright Blue", "Light Blue", 
																			 "Blue Celeste")])
	) +
	labs(
		title = chart_details$title,
		subtitle = format_subtitle(chart_details$subtitle, .width = 110),
		legend = NULL,
		x = "median months from offence being committed, Crown Court cases only, 2018",
		y = NULL,
		colour = NULL
	) +
	theme_cjcharts() +
	theme(
		legend.box.margin = margin(0, 0, 0, 0),
		legend.direction = "vertical",
		legend.margin = margin(0, 0, 0, 0),
		panel.grid.major.x = element_line(),
		panel.grid.minor.x = element_line(),
		panel.grid.major.y = element_blank()
	)
```
`r chart_details$subtitle`

```{r display plot, echo=FALSE, include=TRUE}
add_logo(chart + labs(title = NULL, subtitle = NULL), 
				 chart_details$source_title, chart_details$id)
```

[larger image](../`r chart_details$id`.png)
| [annotated R code to produce this chart](https://github.com/mpjashby/lesscrime.info/blob/master/content/post/`r chart_details$id`.Rmd)

Data source: [`r chart_details$source_title`](`r chart_details$source_url`)

```{r export chart}
# save PNG for social media
ggsave(
	filename = paste0(chart_details$id, ".png"), 
	plot = add_logo(chart, chart_details$source_title, chart_details$id), 
	device = "png", width = 600 / 72, height = 400 / 72, units = "in"
)
```
