---
title: "Chart: When police use force, they rarely cause injury"
author: Matt Ashby
date: '2019-11-25'
slug: use-of-force
categories:
  - Crime and justice chart of the week
tags:
  - police
  - criminal justice
  - use of force
---

```{r set knitr options, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, include=FALSE)
```

```{r set chart parameters}
chart_details <- list(
	id = "use-of-force",
	title = "When police use force, they rarely cause injury",
	subtitle = "Police reported using force on over 300,000 occasions last year, or about 850 each day, with most incidents involving either handcuffing or other restraint. Almost all force used by police resulted in no injury to the person force was used against. When officers did injure people, the injuries were usually minor. However, since these are new statistics there is likely to be some under-reporting, especially of minor incidents.",
	source_url = "https://www.gov.uk/government/statistics/police-use-of-force-statistics-england-and-wales-april-2017-to-march-2018",
	source_title = "Home Office, 2018"
)
```

```{r load packages and helper}
# custom packages not loaded by helpers.R
library("reticulate")

# load this after loading custom packages
source(here::here("helpers.R"))
```

```{r get and tidy data}
if (!file.exists(paste0(chart_details$id, "-data.csv.gz"))) {
	
	# download most-recent data
	new_data_file <- tempfile(fileext = ".ods")
	new_csv_file <- paste0(new_data_file, ".csv")
	GET("https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/764895/police-use-of-force-apr2017-mar2018-hosb3018-tables.ods", write_disk(new_data_file))
	
	# convert new data from ODS to CSV and read
	source_python(here::here("ods_to_csv.py"))
	ods_to_csv(new_data_file, "Table_11", new_csv_file)
	tidy_data <- new_csv_file %>% 
		read_csv(skip = 4) %>% 
		slice(1:6) %>% 
		drop_na() %>% 
		gather("injury", "count", -1) %>% 
		rename(injured = 1)
	
	# save tidy data
	write_csv(tidy_data, paste0(chart_details$id, "-data.csv.gz"))	
	
} else {
	
	# load tidy data
	tidy_data <- read_csv(paste0(chart_details$id, "-data.csv.gz"))
	
}
```

```{r prepare data for chart}

# set number of columns in the chart grid, from which the number of rows will
# be calculated
cols <- 10

# get total number of incidents
total_incidents <- tidy_data %>% 
	filter(injured == "Total incidents", injury == "Total incidents") %>% 
	pluck("count", 1)

# If `injured` == "Yes" then note the type of injury, if `injured` == "No" then
# assume person not injured as a result of use of force, otherwise (i.e. 
# `injured` %in% c("Unknown", "Not reported")) report as unknown

chart_data <- tidy_data %>% 
	mutate(category = case_when(
		injured == "Yes" & injury == "Minor" ~ "minor injury",
		injured == "Yes" & injury %in% c("Death", "Severe") ~ 
			"severe injury or death",
		injured == "Yes" & injury == "Not reported" ~ "not known if any injury",
		injured == "No" & injury == "Total incidents" ~ "no injury",
		injured %in% c("Unknown", "Not reported") & injury == "Total incidents" ~
			"not known if any injury",
		TRUE ~ NA_character_
	)) %>% 
	drop_na() %>% 
	group_by(category) %>% 
	summarise(count = sum(count)) %>% 
	mutate(
		category = ifelse(category == "severe injury", "severe injury or death",
											category),
		category = fct_relevel(fct_rev(factor(category)), "no injury", 
													 "minor injury"),
		permille = round((count / sum(count)) * 1000),
		label = paste0(category, " (", 
									 scales::number(permille, accuracy = 0.1, scale = 0.1, 
									 							 suffix = "%"), 
									 ")")
	) %>% 
	arrange(category) %>% 
	# as_factor() takes order from the data, which are sorted by category
	mutate(category = as_factor(label)) %>% 
	uncount(.$permille) %>% 
	select(category) %>% 
	group_by(category) %>% 
	mutate(
		cell = row_number() - 1,
		row = floor(cell / (cols)),
		col = cell - (row * cols)
	)

# add chart labels
chart_labels <- tribble(
	~x, ~y, ~xend, ~yend, ~category, ~label, ~hjust, ~vjust, ~curve,
	6, 7, 9, 8, "minor injury (5.7%)", balance_lines("minor injuries are those that only require simple first aid", 2), "left", "center", "right",
	1, 1, 4, 4, "severe injury or death (0.1%)", balance_lines("about 400 recorded police uses of force resulted in severe injury (a fracture, deep cut or injury requiring formal admission to hospital) or death", 2), "left", "top", "right",
	6, 5, 9, 5, "not known if any injury (6.0%)", balance_lines("these are experimental statistics, so some data are missing or unclear, possibly due to data-entry errors", 2), "left", "center", "right"
) %>% 
	# order factor levels according to order in chart data, to maintain facet and
	# legend order
	mutate(category = factor(category, levels = levels(chart_data$category)))

```

```{r build plot}
chart <- ggplot(chart_data, aes(x = row, y = col, fill = category)) + 
	geom_tile(colour = "white") + 
	# add explanatory labels
	geom_curve(aes(x = x, y = y, xend = xend, yend = yend),
						 data = filter(chart_labels, curve == "right"), inherit.aes = FALSE, 
						 curvature = elements$label_line_curvature, 
						 colour = elements$label_line_colour, 
						 arrow = elements$label_arrow, show.legend = FALSE) +
	geom_segment(aes(x = x, y = y, xend = xend, yend = yend),
						 data = filter(chart_labels, curve == "straight"), 
						 inherit.aes = FALSE, colour = elements$label_line_colour, 
						 arrow = elements$label_arrow, show.legend = FALSE) +
	geom_curve(aes(x = x, y = y, xend = xend, yend = yend),
						 data = filter(chart_labels, curve == "left"), inherit.aes = FALSE, 
						 curvature = elements$label_line_curvature * -1, 
						 colour = elements$label_line_colour, 
						 arrow = elements$label_arrow, show.legend = FALSE) +
	geom_label(aes(x = xend, y = yend, label = label, hjust = hjust, 
								 vjust = vjust),
						data = chart_labels, inherit.aes = FALSE, 
						colour = elements$label_text_colour,
						fill = elements$label_text_fill, size = elements$label_text_size, 
						lineheight = elements$label_text_lineheight,
						label.size = NA, show.legend = FALSE) +
	# end of explanatory labels
	scale_x_continuous(expand = c(0, 0), position = "top") +
	scale_y_reverse() +
  scale_fill_manual(
    values = unname(ucl_colours_list[c("Orange", "Light Blue", "Dark Green",
                                       "Mid Purple")])
  ) +
	coord_equal() + 
	facet_grid(rows = vars(category), labeller = label_wrap_gen(width = 10), 
						 switch = "y") + 
	labs(
		title = chart_details$title,
		subtitle = format_subtitle(chart_details$subtitle),
		legend = NULL,
		x = paste("each square represents 0.1% of recorded police uses of force in",
							"2017–18, or about", 
							scales::number(total_incidents / 1000, accuracy = 10, 
														 big.mark = ","), "incidents"),
		y = NULL
	) +
	theme_cjcharts() +
	theme(
		axis.line.y = element_line(colour = "grey92"),
		axis.text = element_blank(),
		axis.ticks = element_blank(),
		axis.title.x = element_text(hjust = 0),
		axis.title.y = element_text(hjust = 0.5),
		legend.position = "none",
		panel.grid = element_blank(),
		strip.placement = "outside",
		strip.text.y = element_text(angle = 180, hjust = 1)
	)

```

`r chart_details$subtitle`

```{r display plot, echo=FALSE, include=TRUE}
add_logo(chart + labs(title = NULL, subtitle = NULL), 
				 chart_details$source_title, chart_details$id)
```

[larger image](../`r chart_details$id`.png)
| [annotated R code to produce this chart](https://github.com/mpjashby/lesscrime.info/blob/master/content/post/`r chart_details$id`.Rmd)

Data source: [`r chart_details$source_title`](`r chart_details$source_url`)


```{r export chart}
# save PNG for social media
ggsave(
	filename = paste0(chart_details$id, ".png"), 
	plot = add_logo(chart, chart_details$source_title, chart_details$id), 
	device = "png", width = 600 / 72, height = 400 / 72, units = "in"
)
```
