---
title: "Worry about many types of ASB is at its lowest level for 20 years"
author: Matt Ashby
date: '2023-04-21'
slug: asb-trends
categories:
  - Crime and justice chart of the week
tags:
  - ASB
  - trends
  - CSEW
  - perceptions
subtitle: ''
summary: ''
authors: []
lastmod: '2023-04-21T19:01:54+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


```{r set-knitr-options, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, include = FALSE, dev = "ragg_png")
```

```{r setup}
# Custom packages not loaded by helpers.R
library(readxl)

# Load this after loading custom packages
source(here::here("helpers.R"))

chart_details <- list(
	id = "asb-trends",
	title = "Worry about many types of ASB is at its lowest level for 20 years",
	subtitle = "The Crime Survey for England and Wales asks people every year if they are worried about different types of anti-social behaviour (ASB) in the area where they live. For many types of ASB, in 2022 the percentage of people saying many types of ASB were a very/fairly big problem in their area was at or near its lowest level since records began in 2002.",
	source_url = "https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice/datasets/crimeinenglandandwalesannualsupplementarytables",
	source_title = "Office for National Statistics"
)
```

```{r load-data}
if (!file.exists(str_glue("{chart_details$id}.csv.gz"))) {
  
  data_file <- tempfile(fileext = ".xlsx")
  download.file(
    url = "https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/crimeandjustice/datasets/crimeinenglandandwalesannualsupplementarytables/march2020/annualsupplementarytablesmar201.xlsx", 
    destfile = data_file
  )
  
  tidy_data <- data_file |> 
    read_excel(
        sheet = "Table S34", 
        skip = 3, 
        na = c("", ":"), 
        col_types = "text"
    ) |> 
    clean_names() |> 
    slice(3, 7:14) |> 
    select(type = x1, starts_with("apr_")) |> 
    pivot_longer(cols = -type, names_to = "year", values_to = "percentage") |> 
    mutate(
      type = str_remove(type, "[\\d\\,]+?$"),
      year = str_sub(year, start = 15, end = 16), 
      year = str_glue("20{year}"), 
      across(c(year, percentage), parse_number),
      percentage = percentage / 100
    ) |> 
    filter(!is.na(type))
  
  write_csv(tidy_data, str_glue("{chart_details$id}.csv.gz"))
  
} else {
  
  tidy_data <- read_csv(str_glue("{chart_details$id}.csv.gz"))
  
}
```

```{r wrangle-data}
# Add 2022 data manually, from Table F20 of
# https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice/datasets/crimeinenglandandwalesotherrelatedtables
data_2022 <- tribble(
  ~type, ~year, ~percentage,
  "Abandoned or burnt-out cars", 2022, 2.29055253432124,
  "High level of perceived anti-social behaviour", 2022, 8.035801551349,
  "Noisy neighbours or loud parties", 2022, 8.69734313581641,
  "People being drunk or rowdy in public places", 2022, 12.2719758693247,
  "People using or dealing drugs", 2022, 21.6116153941217,
  "Rubbish or litter lying around", 2022, 29.2063861999025,
  "Teenagers hanging around on the streets", 2022, 12.6778098940408, 
  "Vandalism, graffiti and other deliberate damage to property", 2022, 13.2306151331332
) |> 
  mutate(percentage = percentage / 100)

chart_data <- tidy_data |> 
  bind_rows(data_2022) |> 
  mutate(
    current_rate = last(percentage),
    year_ending = ymd(str_glue("{year}-03-31")),
    .by = type
  ) |> 
  mutate(
    fill = type == "High level of perceived anti-social behaviour",
    type = fct_reorder(type, current_rate, .desc = TRUE),
    type = fct_relevel(type, "High level of perceived anti-social behaviour"),
    type = fct_recode(
      type,
      "High level of ASB overall*" = "High level of perceived anti-social behaviour"
    )
  )
  
label_data <- chart_data |> 
  filter(year %in% c(2010, max(chart_data$year))) |> 
  mutate(
    change = scales::number(
      (last(percentage) - first(percentage)) / first(percentage), 
      accuracy = 1, 
      scale = 100, 
      suffix = "%",
      style_positive = "plus",
      style_negative = "minus"
    ),
    .by = type
  ) |> 
  mutate(
    colour = current_rate > 0.1,
    label = case_when(
      year == max(year) & type == first(type) ~ 
        str_glue("**{change}** change, 2010–22"),
      year == max(year) ~ str_glue("**{change}**"), 
      TRUE ~ NA
    )
  ) |> 
  filter(!is.na(label))
```

```{r}
chart <- chart_data |> 
  ggplot(aes(x = year_ending, y = percentage)) +
  geom_area(colour = NA, fill = "white") +
  geom_area(
    aes(fill = fill),
    alpha = 0.67, 
    colour = NA
  ) +
  geom_line(aes(colour = fill), linewidth = 1) +
  geom_vline(
    aes(xintercept = ymd("2010-03-31")), 
    colour = elements$average_line_colour,
    linetype = elements$average_line_linetype
  ) +
  geom_richtext(
    aes(y = 0, label = label), 
    data = label_data,
    fill = NA,
    hjust = 1,
    label.size = NA,
    lineheight = elements$label_text_lineheight,
    size = elements$label_text_size,
    vjust = 0
  ) +
  geom_point(
    aes(colour = fill),
    data = label_data,
    size = 2
  ) +
  scale_x_date(
    expand = expansion(0.025)
  ) +
  scale_y_continuous(
    breaks = c(0, 0.1, 0.2, 0.3),
    limits = c(0, NA), 
    labels = scales::label_percent(), 
    expand = expansion(c(0, 0.05)),
    position = "right"
  ) +
  scale_fill_manual(
    values = c(
      `TRUE` = ucl_colours_list[["Bright Red"]], 
      `FALSE` = ucl_colours_list[["Bright Blue"]]
    ),
    aesthetics = c("colour", "fill")
  ) +
  facet_wrap(vars(type), labeller = label_wrap_gen(width = 23), ncol = 4) +
  labs(
		title = chart_details$title,
		subtitle = chart_details$subtitle,
		caption = "\\* This is a composite measure based on how big a problem a respondent said they felt each of the specific types of ASB were in their area.",
    x = NULL,
    y = "percentage of people saying this type of\nASB is a very/fairly big problem in their area"
  ) +
  theme_cjcharts() +
  theme(
    legend.position = "none",
    plot.caption = element_textbox_simple(margin = margin(t = 12)),
		plot.title = element_textbox_simple(),
		plot.subtitle = element_textbox_simple(margin = margin(t = 12, b = 6))
  )
```

`r chart_details$subtitle`

```{r display-plot, echo=FALSE, include=TRUE, warning=FALSE}
add_logo(
  chart + labs(title = NULL, subtitle = NULL), 
  chart_details$source_title, 
  chart_details$id
)
```

[larger image](`r chart_details$id`.png)
| [annotated R code to produce this chart](https://github.com/mpjashby/lesscrime.info/blob/master/content/post/`r chart_details$id`.Rmd)

Data source: [`r chart_details$source_title`](`r chart_details$source_url`)

```{r export-chart}
# Save PNG for social media
ggsave(
	filename = paste0(chart_details$id, ".png"), 
	plot = add_logo(chart, chart_details$source_title, chart_details$id), 
	device = "png", 
	width = 600 / 72, 
	height = 500 / 72, 
	units = "in", 
	bg = "white"
)
```
