---
title: "Rates of most common crimes have dropped since 2010"
author: Matt Ashby
date: '2023-04-21'
slug: crime-since-2010
categories:
  - Crime and justice chart of the week
tags:
  - crime
  - trends
  - CSEW
subtitle: ''
summary: ''
authors: []
lastmod: '2023-04-21T15:09:44+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r set-knitr-options, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, include = FALSE, dev = "ragg_png")
```

```{r setup}
# Custom packages not loaded by helpers.R
library(readxl)

# Load this after loading custom packages
source(here::here("helpers.R"))

chart_details <- list(
	id = "crime-since-2010",
	title = "Rates of most common crimes have dropped since 2010",
	subtitle = "The Crime Survey for England and Wales is based on a large, representative sample of households. The survey measures crime in a consistent way that is not affected by changes in police recording of crime, so it can be used to reliably track changes in crime over time. Data from the Crime Suvey show that the proportion of people who say they or their household has been a victim of most common types of crime such as violence and burglary has dropped substantially since 2010.",
	source_url = "https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice/datasets/crimeinenglandandwalesappendixtables",
	source_title = "Office for National Statistics"
)
```

```{r load-data}
if (!file.exists("crime-since-2010.csv.gz")) {
  
  data_file <- tempfile(fileext = ".xlsx")
  download.file(
    url = "https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/crimeandjustice/datasets/crimeinenglandandwalesappendixtables/yearendingseptember2022/appendixtablescorrectionyesept22.xlsx", 
    destfile = data_file
  )
  
  tidy_data <- data_file |> 
    read_excel(
      sheet = "Table A3", 
      skip = 9, 
      na = c("", "[x]"), 
      col_types = "text"
    ) |> 
    clean_names() |> 
    # Remove the second table in the sheet, which is to the right of the first
    select(1:29) |> 
    select(
      offence = offence_group_note_4_1, 
      starts_with("apr"), 
      oct_2021_to_sep_2022_note_6
    ) |> 
    pivot_longer(
      cols = -offence, 
      names_to = "year", 
      values_to = "prevalence"
    ) |> 
    mutate(
      offence = str_remove(offence, " \\[.+?\\]$"),
      year = str_sub(year, start = 17, end = 20),
      across(c(year, prevalence), parse_number),
      prevalence = prevalence / 100
    )
  
  write_csv(tidy_data, "crime-since-2010.csv.gz")
  
} else {
  
  tidy_data <- read_csv("crime-since-2010.csv.gz")
  
}
```

```{r wrangle-data}
chart_data <- tidy_data |> 
  mutate(
    offence = case_match(
      offence,
      "Violence with injury" ~ "Violence with injury",
      "Violence without injury" ~ "Violence without injury",
      "ROBBERY" ~ "Personal robbery",
      "Domestic burglary" ~ "Domestic burglary",
      "Theft from the person" ~ "Theft from the person",
      "Theft from vehicles" ~ "Theft from a vehicle",
      "Theft of vehicles" ~ "Theft of a vehicle",
      "Bicycle theft" ~ "Bicycle theft",
      "CRIMINAL DAMAGE" ~ "Criminal damage",
      .default = NA_character_
    )
  ) |> 
  filter(!is.na(offence), year >= 2010) |> 
  # The data contains multiple prevalence values for some crimes, constructed
  # using different denominators. The first value is for a denominator of all
  # households and the later ones are for households who could be victimised,
  # e.g. households with vehicles for vehicle theft. The more-specific 
  # denominators are better, so we will use those.
  summarise(across(everything(), last), .by = c(offence, year)) |> 
  mutate(
    change = scales::number(
      (last(prevalence) - first(prevalence)) / first(prevalence), 
      accuracy = 1, 
      scale = 100, 
      prefix = "**",
      suffix = "%**", 
      style_negative = "minus"
    ),
    .by = offence
  ) |> 
  mutate(
    offence = factor(
      offence,
      levels = c(
        "Violence with injury", "Violence without injury", "Personal robbery",
        "Domestic burglary", "Theft from the person", "Criminal damage", 
        "Bicycle theft", "Theft of a vehicle", "Theft from a vehicle"
      )
    ),
    label = case_when(
      year == max(year) & offence == "Violence with injury" ~ 
        str_glue("change from 2010<br>to 2022: {change}"),
      year == max(year) ~ change, 
      TRUE ~ NA
    )
  )
```

```{r}
chart <- chart_data |> 
  ggplot(aes(x = year, y = prevalence)) +
  geom_area(colour = NA, fill = "white") +
  geom_area(
    alpha = 0.67, 
    colour = NA, 
    fill = ucl_colours_list[["Bright Blue"]]
  ) +
  geom_richtext(
    aes(label = label), 
    na.rm = TRUE, 
    colour = "white",
    hjust = 1,
    fill = NA,
    label.size = NA,
    lineheight = elements$label_text_lineheight,
    size = elements$label_text_size,
    vjust = 1
  ) +
  geom_line(colour = ucl_colours_list[["Bright Blue"]], linewidth = 1) +
  geom_point(
    data = filter(chart_data, !is.na(label)), 
    colour = ucl_colours_list[["Bright Blue"]],
    size = 2
  ) +
  scale_x_continuous(
    breaks = c(2010, 2016, 2022), 
    expand = expansion(0.025)
  ) +
  scale_y_continuous(
    limits = c(0, NA), 
    labels = scales::label_percent(), 
    expand = expansion(c(0, 0.05)),
    position = "right",
    n.breaks = 3
  ) +
  facet_wrap(vars(offence), scales = "free_y") +
  labs(
		title = chart_details$title,
		subtitle = chart_details$subtitle,
    x = NULL,
    y = "percentage of people/households saying that they\nhad been a victim at least once during the year"
  ) +
  theme_cjcharts() +
  theme(
    legend.position = "none",
		plot.title = element_textbox_simple(),
		plot.subtitle = element_textbox_simple(margin = margin(t = 12, b = 6))
  )
```

`r chart_details$subtitle`

```{r display-plot, echo=FALSE, include=TRUE, warning=FALSE}
add_logo(
  chart + labs(title = NULL, subtitle = NULL), 
  chart_details$source_title, 
  chart_details$id
)
```

[larger image](`r chart_details$id`.png)
| [annotated R code to produce this chart](https://github.com/mpjashby/lesscrime.info/blob/master/content/post/`r chart_details$id`.Rmd)

Data source: [`r chart_details$source_title`](`r chart_details$source_url`)

```{r export-chart}
# Save PNG for social media
ggsave(
	filename = paste0(chart_details$id, ".png"), 
	plot = add_logo(chart, chart_details$source_title, chart_details$id), 
	device = "png", 
	width = 600 / 72, 
	height = 500 / 72, 
	units = "in", 
	bg = "white"
)
```
